name: CI

env:
  APPLICATION_NAME : "Python App"
  COMMIT_MSG       : "Commit SHA: ${{ github.sha }}"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: la before checkout
        run: ll
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: la after checkout
        run: ll

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  teste:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Print ENV vars
        run: |
          echo "Message-1: ${{env.APPLICATION_NAME}}",
          echo "Message-2: ${{env.COMMIT_MSG}}"
