name: CI

env:
  APPLICATION_NAME : "Python App"
  COMMIT_MSG       : "Commit SHA: ${{ github.sha }}"
  BUILD_KEY : "Build Global"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      BUILD_KEY : "Build1"

    steps:
      - name: la before checkout
        run: ls -la
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: la after checkout
        run: ls -la

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Print Build ENV Var
        run: echo ${{ env.BUILD_KEY }}
  
  test:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Print ENV vars
        run: |
          echo "Message-1: ${{env.APPLICATION_NAME}}",
          echo "Message-2: ${{env.COMMIT_MSG}}"
